name: Build APK Completo - Prontuário Geriátrico (CORRIGIDO)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Create Capacitor project with TypeScript
      run: |
        mkdir apk-project
        cd apk-project
        npm init -y
        npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/preferences @capacitor/network typescript